#!/usr/bin/env bash
# scripts/test/secrets_test.sh — the secrets init.sh writes into /etc/vigil/env.
#
# init.sh generates two: the consent password (VIGIL_AUTH_PASSWORD) and the
# SkillKey HMAC secret (VIGIL_SKILLKEY_SECRET). They used to be one value in
# two roles, and a SkillKey — handed to every client, kept in chat
# transcripts — was then an HMAC output anyone could test password guesses
# against offline. The boot check (Vigil.Settings.Check) refuses a SkillKey
# secret that does not decode to at least 32 random bytes or that equals the
# password; this checks that what init.sh generates passes it, and that init.sh
# generates and writes the two apart.
#
# The generator is driven for real. init.sh's own step 3 needs root, a
# "vigil" user and a booted host, so what is asserted about it is its text:
# that each secret comes from a call of its own and lands on its own line.
#
# Usage: bash scripts/test/secrets_test.sh

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
INIT_SH="${REPO_ROOT}/scripts/init.sh"

# shellcheck source=scripts/test/harness.sh
source "${SCRIPT_DIR}/harness.sh"

# shellcheck source=scripts/lib.sh
source "${REPO_ROOT}/scripts/lib.sh"

# lib.sh installs `trap summary EXIT`; this suite has nothing to clean up, and
# its verdict is `report`'s, so lib.sh's run summary is not wanted here.
trap - EXIT

# How many bytes a base64 value decodes to, or 0 if it is not base64.
decoded_bytes() {
  printf '%s\n' "$1" | openssl base64 -d 2>/dev/null | wc -c | tr -d ' '
}

## ── 1. What generate_secret prints ───────────────────────────────────────

section "1/2  generate_secret"

first="$(generate_secret)"
second="$(generate_secret)"

bytes="$(decoded_bytes "$first")"
if [ "$bytes" -ge 32 ]; then
  pass "decodes to at least the 32 bytes the boot check asks for (${bytes})"
else
  fail "decodes to at least the 32 bytes the boot check asks for" "got ${bytes}"
fi

if [[ "$first" =~ ^[A-Za-z0-9+/]+$ ]]; then
  pass "is one line of base64 with no padding"
else
  fail "is one line of base64 with no padding"
fi

if [ "$first" != "$second" ]; then
  pass "two calls give two different secrets"
else
  fail "two calls give two different secrets"
fi

## ── 2. What init.sh does with it ─────────────────────────────────────────

section "2/2  init.sh generates both secrets apart and writes both"

init_text="$(cat "$INIT_SH")"

assert_contains() {
  case "$2" in
    *"$3"*) pass "$1" ;;
    *) fail "$1" "expected to find: $3" ;;
  esac
}

# The needles are init.sh's own text, expansions and all, so single-quoted.
# shellcheck disable=SC2016
assert_contains "the consent password is generated by a call of its own" \
  "$init_text" 'AUTH_PASSWORD="$(generate_secret)"'
# shellcheck disable=SC2016
assert_contains "the SkillKey secret is generated by a call of its own" \
  "$init_text" 'SKILLKEY_SECRET="$(generate_secret)"'
# shellcheck disable=SC2016
assert_contains "the env file carries the consent password" \
  "$init_text" 'VIGIL_AUTH_PASSWORD=${AUTH_PASSWORD}'
# shellcheck disable=SC2016
assert_contains "the env file carries the SkillKey secret" \
  "$init_text" 'VIGIL_SKILLKEY_SECRET=${SKILLKEY_SECRET}'

example="$(cat "${REPO_ROOT}/deploy/vigil.env.example")"
assert_contains "deploy/vigil.env.example names the SkillKey secret" \
  "$example" 'VIGIL_SKILLKEY_SECRET='

report
